[versions]
micronaut = "4.6.3"
micronaut-test = "4.5.0"
micronaut-docs = "2.0.0"
groovy = "4.0.24"
spock = "2.3-groovy-4.0"
junit5 = "5.12.0"
junit-platform-launcher="1.12.0"

[libraries]
spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
